export const inputsLength = {
  name: 5,
  address: 5,
  mobile: 11,
  phone: 10,
  email: 10,
  password: 5,
  language: 2,
  permissionName: 3,
  routeName: 3,
  branchName: 3,
  govName: 3,
  govCode: 2,
  cityName: 3,
  todoName: 5,
};
