export const PermissionsNames = {
  addUser: 'addUser',
  updateUser: 'updateUser',
  deleteUser: 'deleteUser',
  addRoute: 'addRoute',
  updateRoute: 'updateRoute',
  deleteRoute: 'deleteRoute',
  addGov: 'addGov',
  updateGov: 'updateGov',
  deleteGov: 'deleteGov',
  addCity: 'addCity',
  updateCity: 'updateCity',
  deleteCity: 'deleteCity',
  addTodo: 'addTodo',
  updateTodo: 'updateTodo',
  deleteTodo: 'deleteTodo',
  addBranch: 'addBranch',
  updateBranch: 'updateBranch',
  deleteBranch: 'deleteBranch',
};
